### PR TITLE
Fixed issues - 1.1

### PR DESCRIPTION
**Pull request by AakashSahani**

### CODE REVIEW

**Comment by sbmsr** [comment]
Hi @AakashSahani 👋

I see the tests are failing. Let me know if you need help!

**Comment by AakashSahani** [comment]
Hi @sbmsr, I will give it one more attempt 😥. I will let you know if it still fails.🙂

**Comment by AakashSahani** [comment]
@sbmsr, Could you help me with the desktop menu? I have deployed it on vercel. The desktop menu is not visible on mobile. I used display: none; using on the desktop nav id.
https://javascript-landing-page.vercel.app/

**Comment by sbmsr** [comment]
> @sbmsr, Could you help me with the desktop menu? I have deployed it on vercel. The desktop menu is not visible on mobile. I used display: none; using on the desktop nav id. I don't know why the test is failing. [javascript-landing-page.vercel.app](https://javascript-landing-page.vercel.app/)

@AakashSahani You're close - in the issue description (#2 ) there is an important detail: 

`While doing this task, stick to using our existing css classes. Our styles.css is fairly messy, and we don't want to add any more new styles.`

I hope that helps 😉. Let me know if it doesn't!

**Comment by AakashSahani** [comment]
Finally!!🥳 Thank you for your help @sbmsr

**Pull request closed without merging**
